### ISSUE TITLE
Wide table gets chopped when printing

### ISSUE THREAD

**Issue by mingyuan-xia** [outlinejs/outlinejs#56]
After having the resizable table, printing a wide table (to a printer or to a PDF) gets columns chopped on the right.
There is no way to control if we want all columns fitted in (no matter how ugly they are).
Also, the on-screen view of the table is much different from the printed version, which makes it hard to anticipate how a PDF version of the document would be.

**Comment by faxioman** [comment]
Hi @mingyuan-xia I think you choose the wrong repo. This is an (old) js micro-framework.

**Comment by mingyuan-xia** [comment]
really sorry, wrong place!
